In [148]:
#import packages
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [149]:
#read data
file_path = '.\dataset'
df_raw_data = pd.read_csv(os.path.join(file_path,'open-beer-database.csv'),sep=',')
df_raw_data.head()

,Name,id,brewery_id,cat_id,style_id,Alcohol By Volume,International Bitterness Units,Standard Reference Method,Universal Product Code,filepath,...,last_mod,Style,Category,Brewer,Address,City,State,Country,Coordinates,Website
0,Scottish Ale,1495,347,1,15,5.8,0.0,0.0,0.0,NaN,...,2010-07-23T01:30:00+05:30,Scotch Ale,British Ale,Carlyle Brewing,215 East State Street,Rockford,Illinois,United States,"42.2689, -89.0907",NaN
1,Het Kapittel Pater,1509,301,-1,-1,0.0,0.0,0.0,0.0,NaN,...,2010-07-23T01:30:00+05:30,NaN,NaN,Brouwerij Van Eecke,Douvieweg 2,Watou,West-Vlaanderen,Belgium,"50.8612, 2.6615",NaN
2,Export Premium,1516,785,-1,-1,5.4,0.0,0.0,0.0,NaN,...,2010-07-23T01:30:00+05:30,NaN,NaN,Licher Privatbrauerei,In den Hardtberggrten,Lich,Hessen,Germany,"50.5208, 8.8166",NaN
3,Bee Sting Honey Ale,1527,604,3,26,5.9,0.0,0.0,0.0,NaN,...,2010-07-23T01:30:00+05:30,American-Style Pale Ale,North American Ale,Great Divide Brewing,2201 Arapahoe Street,Denver,Colorado,United States,"39.7539, -104.989",http://www.greatdivide.com/
4,PranQster Belgian Ale,1540,919,-1,-1,7.6,0.0,0.0,0.0,NaN,...,2010-07-23T01:30:00+05:30,NaN,NaN,North Coast Brewing Company,455 North Main Street,Fort Bragg,California,United States,"39.4466, -123.806",http://www.northcoastbrewing.com/home.htm

In [150]:
df_raw_data['Alcohol By Volume']

0       5.8
1       0.0
2       5.4
3       5.9
4       7.6
5       0.0
6       0.0
7       4.5
8       5.0
9       0.0
10      0.0
11      0.0
12      7.0
13      4.7
14      5.2
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      9.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      5.6
27      0.0
28      0.0
29      0.0
       ...
5943    7.0
5944    9.0
5945    9.2
5946    5.0
5947    8.0
5948    7.0
5949    0.0
5950    4.8
5951    4.8
5952    0.0
5953    5.0
5954    5.2
5955    4.3
5956    5.7
5957    5.0
5958    9.6
5959    5.2
5960    5.2
5961    4.3
5962    6.0
5963    4.9
5964    9.0
5965    5.8
5966    8.0
5967    5.3
5968    0.0
5969    5.7
5970    5.5
5971    5.1
5972    5.4
Name: Alcohol By Volume, Length: 5973, dtype: float64

In [151]:
#primary search
print('Number of Instances:',len(df_raw_data))
print('\nMissing Vaules\n', df_raw_data.isnull().sum())
print('\nValues with zero(presumably missing value as well)\n',(df_raw_data==0).sum())

Number of Instances: 5973

Missing Vaules
 Name                                10
id                                   0
brewery_id                          10
cat_id                              23
style_id                            24
Alcohol By Volume                   25
International Bitterness Units      25
Standard Reference Method           25
Universal Product Code              29
filepath                          5948
Description                       3927
add_user                            43
last_mod                            73
Style                             1507
Category                          1507
Brewer                              25
Address                            782
City                                52
State                              349
Country                             25
Coordinates                        227
Website                           3094
dtype: int64

Values with zero(presumably missing value as well)
 Name                                 0
id                                   0
brewery_id                           0
cat_id                               0
style_id                             0
Alcohol By Volume                 2891
International Bitterness Units    5929
Standard Reference Method         5935
Universal Product Code            5938
filepath                             0
Description                          0
add_user                             0
last_mod                             0
Style                                0
Category                             0
Brewer                               0
Address                              0
City                                 0
State                                0
Country                              0
Coordinates                          0
Website                              0
dtype: int64

In [152]:
#drop columns with too many missing values
df1 = df_raw_data.drop(['filepath','Description','Website','International Bitterness Units','Standard Reference Method','Universal Product Code'], axis=1)

In [153]:
df1.head()
#This data is WRECKED!!!!!!!!!

,Name,id,brewery_id,cat_id,style_id,Alcohol By Volume,add_user,last_mod,Style,Category,Brewer,Address,City,State,Country,Coordinates
0,Scottish Ale,1495,347,1,15,5.8,0,2010-07-23T01:30:00+05:30,Scotch Ale,British Ale,Carlyle Brewing,215 East State Street,Rockford,Illinois,United States,"42.2689, -89.0907"
1,Het Kapittel Pater,1509,301,-1,-1,0.0,0,2010-07-23T01:30:00+05:30,NaN,NaN,Brouwerij Van Eecke,Douvieweg 2,Watou,West-Vlaanderen,Belgium,"50.8612, 2.6615"
2,Export Premium,1516,785,-1,-1,5.4,0,2010-07-23T01:30:00+05:30,NaN,NaN,Licher Privatbrauerei,In den Hardtberggrten,Lich,Hessen,Germany,"50.5208, 8.8166"
3,Bee Sting Honey Ale,1527,604,3,26,5.9,0,2010-07-23T01:30:00+05:30,American-Style Pale Ale,North American Ale,Great Divide Brewing,2201 Arapahoe Street,Denver,Colorado,United States,"39.7539, -104.989"
4,PranQster Belgian Ale,1540,919,-1,-1,7.6,0,2010-07-23T01:30:00+05:30,NaN,NaN,North Coast Brewing Company,455 North Main Street,Fort Bragg,California,United States,"39.4466, -123.806"

In [154]:
print('Number of Brewery ID: ', len(df1.brewery_id.unique()))
print('\nNumber of Style :', len(df1.Style.unique()),'\n List of Style\n', df1.Style.unique())
print('\nNumber of Category :', len(df1.Category.unique()),'\n List of Category\n', df1.Category.unique())
print('\nNumber of City :',len(df1.City.unique()))
print('\nNumber of State :',len(df1.State.unique()))
print('\nNumber of Country :',len(df1.Country.unique()))

Number of Brewery ID:  1333

Number of Style : 69
 List of Style
 ['Scotch Ale' nan 'American-Style Pale Ale' 'South German-Style Hefeweizen'
 'Traditional German-Style Bock' 'American-Style Amber/Red Ale'
 'German-Style Schwarzbier' 'American-Style Stout' 'Old Ale' 'Porter'
 'American-Style Lager' 'English-Style Pale Mild Ale'
 'American-Style Brown Ale' 'Light American Wheat Ale or Lager'
 'Belgian-Style Fruit Lambic' 'Winter Warmer'
 'American-Style India Pale Ale' 'American-Style Light Lager'
 'Belgian-Style White' 'German-Style Oktoberfest'
 'American-Style Imperial Stout' 'German-Style Pilsener'
 'Other Belgian-Style Ales' 'Extra Special Bitter' 'Belgian-Style Tripel'
 'Imperial or Double India Pale Ale' 'South German-Style Weizenbock'
 'Oatmeal Stout' 'Golden or Blonde Ale' 'German-Style Brown Ale/Altbier'
 'Fruit Beer' 'German-Style Heller Bock/Maibock'
 'Special Bitter or Best Bitter' 'Belgian-Style Dark Strong Ale'
 'Belgian-Style Pale Strong Ale' 'American-Style Barley Wine Ale'
 'Dark American-Belgo-Style Ale' 'Classic English-Style Pale Ale'
 'German-Style Doppelbock' 'American Rye Ale or Lager'
 'Belgian-Style Dubbel' 'American-Style Cream Ale or Lager'
 'Irish-Style Red Ale' 'Sweet Stout' 'Ordinary Bitter'
 'French & Belgian-Style Saison' 'English-Style India Pale Ale'
 'Scottish-Style Light Ale' 'Pumpkin Beer' 'Belgian-Style Pale Ale'
 'Belgian-Style Quadrupel' 'Herb and Spice Beer'
 'American-Style Strong Pale Ale' 'Strong Ale' 'Specialty Beer'
 'Smoke Beer' 'Vienna-Style Lager' 'Baltic-Style Porter'
 'Specialty Honey Lager or Ale' 'Classic Irish-Style Dry Stout'
 'European Low-Alcohol Lager' 'Imperial or Double Red Ale'
 'Out of Category' 'Kellerbier - Ale' 'Bamberg-Style Bock Rauchbier'
 'American-Style Dark Lager' 'Foreign (Export)-Style Stout'
 'American-Style India Black Ale' 'English-Style Dark Mild Ale']

Number of Category : 10
 List of Category
 ['British Ale' nan 'North American Ale' 'German Ale' 'German Lager'
 'Irish Ale' 'North American Lager' 'Other Style' 'Belgian and French Ale'
 'Other Lager']

Number of City : 947

Number of State : 161

Number of Country : 62

In [155]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = df1.fillna('NaN')['Category'].tolist()

corpus2 = []
for word in corpus:
    word = word.replace(" ","_")
    corpus2.append(word)

freq = {}
for word in corpus2:
    freq[word] = freq.get(word,0) +1
print('List and Number of Category\n',freq)

List and Number of Category
 {'British_Ale': 321, 'NaN': 1507, 'North_American_Ale': 2014, 'German_Ale': 222, 'German_Lager': 444, 'Irish_Ale': 290, 'North_American_Lager': 572, 'Other_Style': 271, 'Belgian_and_French_Ale': 328, 'Other_Lager': 4}

In [156]:
sum(df1.Category.isnull() == df1.Style.isnull())
#If there is value in category, there is value in Style, and if there is no value in category, there is no value in Style

5973

In [163]:
df1 = df1.drop(['id','brewery_id','cat_id','style_id','add_user','last_mod','Style'],axis=1)

In [164]:
df1['Alcohol By Volume'] = df1['Alcohol By Volume'].replace(0,df1['Alcohol By Volume'].mean())
df1

,Name,Alcohol By Volume,Category,Brewer,Address,City,State,Country,Coordinates
0,Scottish Ale,5.800000,British Ale,Carlyle Brewing,215 East State Street,Rockford,Illinois,United States,"42.2689, -89.0907"
1,Het Kapittel Pater,3.379987,NaN,Brouwerij Van Eecke,Douvieweg 2,Watou,West-Vlaanderen,Belgium,"50.8612, 2.6615"
2,Export Premium,5.400000,NaN,Licher Privatbrauerei,In den Hardtberggrten,Lich,Hessen,Germany,"50.5208, 8.8166"
3,Bee Sting Honey Ale,5.900000,North American Ale,Great Divide Brewing,2201 Arapahoe Street,Denver,Colorado,United States,"39.7539, -104.989"
4,PranQster Belgian Ale,7.600000,NaN,North Coast Brewing Company,455 North Main Street,Fort Bragg,California,United States,"39.4466, -123.806"
5,Ale,3.379987,NaN,Bass Brewers,137 High Street,Burton-upon-Trent,Staffordshire,United Kingdom,"52.8046, -1.6281"
6,Gouden Carolus NoÃƒÂ«l,3.379987,NaN,Brouwerij Het Anker,Guido Gezellelaan 49,Mechelen,Antwerpen,Belgium,"51.0325, 4.473"
7,Lager,4.500000,NaN,Binding Brauerei AG,Darmstdter Landstrae 185,Frankfurt am Main,Hessen,Germany,"50.0943, 8.6913"
8,Pilsener,5.000000,NaN,Friesisches Brauhaus zu Jever,Elisabethufer 18,Jever,Niedersachsen,Germany,"53.5755, 7.9016"
9,KÃƒÂ¶lsch,3.379987,NaN,Clner Hofbrau Frh,Am Hof 12-14,Kln,Nordrhein-Westfalen,Germany,"50.9401, 6.957"
10,Pils,3.379987,NaN,Gatz Brauhaus,NaN,Dsseldorf,Nordrhein-Westfalen,Germany,"51.2249, 6.7757"
11,Weissbier,3.379987,German Ale,Schlobrauerei Reckendorf,Mhlweg 18,Reckendorf,Bayern,Germany,"50.0224, 10.83"
12,Bockbier,7.000000,German Lager,Klosterbru Bamberg,Obere Mhlbrcke 1-3,Bamberg,Bayern,Germany,"49.8891, 10.887"
13,Pils,4.700000,NaN,Maisel Bru,Moosstrae 46,Bamberg,Bayern,Germany,"49.8928, 10.9131"
14,Schwarze Weisse,5.200000,NaN,LÃƒÂ¶wenbrÃƒÂ¤u Brauerei,Nymphenburger StraÃƒÅ¸e 4,MÃƒÂ¼nchen,Bayern,Germany,NaN
15,Maximator,3.379987,German Lager,Augustiner-BrÃƒÂ¤u MÃƒÂ¼nchen,Landsberger Strae 35,MÃƒÂ¼nchen,Bayern,Germany,NaN
16,Edelstoff,3.379987,NaN,Augustiner-BrÃƒÂ¤u MÃƒÂ¼nchen,Landsberger Strae 35,MÃƒÂ¼nchen,Bayern,Germany,NaN
17,Native Ale,3.379987,North American Ale,New Glarus Brewing Company,2400 State Highway 69,New Glarus,Wisconsin,United States,"42.8171, -89.6306"
18,Dark Lager,3.379987,German Lager,San Miguel Corporation,PO Box 271,Manila,NaN,Philippines,"14.5833, 120.967"
19,Bootlegger Blonde Ale,3.379987,NaN,Pizzeria Uno Chicago Grill & Brewery,61 US Highway 1 South,Metuchen,New Jersey,United States,"37.2283, -77.3903"
20,Imperial Stout,9.000000,North American Ale,Triumph Brewing of Princeton,138 Nassau Street,Princeton,New Jersey,United States,"40.3507, -74.6583"
21,Horndean Special Bitter / HSB,3.379987,NaN,George Gale & Company,NaN,Portsmouth,Hampshire,United Kingdom,"50.7989, -1.0912"
22,Pale Ale,3.379987,North American Ale,Joshua Huddy's Brew Pub and Grill,NaN,Toms River,New Jersey,United States,"39.9529, -74.201"
23,New Peculier,3.379987,British Ale,Great Dane Pub and Brewing #2,2980 Cahill Main,Fitchburg,Wisconsin,United States,"43.0177, -89.4232"
24,Old Glory American Pale Ale,3.379987,North American Ale,Great Dane Pub and Brewing #2,2980 Cahill Main,Fitchburg,Wisconsin,United States,"43.0177, -89.4232"
25,Golden Blonde,3.379987,NaN,Harvest Moon Brewery / Cafe,392 George Street,New Brunswick,New Jersey,United States,"40.4962, -74.4441"
26,Pacific Coast Ale,5.600000,NaN,Trap Rock Restaurant and Brewery,279 Springfield Avenue,Berkeley Heights,New Jersey,United States,"40.6892, -74.4349"
27,Schwarzbier,3.379987,German Lager,Hereford & Hops Steakhouse and Brewpub #3,2201 Sherman Street,Wausau,Wisconsin,United States,"44.9518, -89.6657"
28,Porter,3.379987,Irish Ale,Corner Pub,100 Main Street,Reedsburg,Wisconsin,United States,"43.5323, -90.0099"
29,Canadian Light,3.379987,North American Lager,Courthouse Pub,1001 South Eighth Street,Manitowoc,Wisconsin,United States,"44.0886, -87.6576"
...,...,...,...,...,...,...,...,...,...
5943,Duet,7.000000,North American Ale,Alpine Beer Company,2351 Alpine Boulevard,Alpine,California,United States,"32.8355, -116.765"
5944,Kryptonite Imperial IPA,9.000000,North American Ale,Iron Hill Brewery - Wilmingon,620 South Madison Street,Wilmington,Delaware,United States,"39.745, -75.5561"
5945,471 IPA,9.200000,North American Ale,Breckenridge Brewery,471 Kalamath Street,Denver,Colorado,United States,"39.7236, -105.001"
5946,Ise Kadoya Stout,5.000000,North American Ale,Nikenjayamochi Kadoya Honten Co.,NaN,NaN,NaN,Japan,NaN
5947,One,8.000000,Belgian and French Ale,(512) Brewing Company,"407 Radam, F200",Austin,Texas,United States,"30.2234, -97.7697"
5948,Conundrum Red Ale,7.000000,North American Ale,Aspen Brewing Company,555 North Mill Street,Aspen,Colorado,United States,NaN
5949,Wheat,3.379987,German Lager,Abita Brewing Company,PO Box 1510,Abita Springs,Louisiana,United States,"30.5049, -89.944"
5950,Dreamweaver,4.800000,Other Style,Troegs Brewing,800 Paxton Street,Harrisburg,Pennsylvania,United States,"40.2559, -76.8715"
5951,Spotted Cow,4.800000,North American Ale,New Glarus Brewing Company,2400 State Highway 69,New Glarus,Wisconsin,United States,"42.8171, -89.6306"
5952,Z Lager,3.379987,North American Lager,Fort Collins Brewery,1900-B East Lincoln Avenue,Fort Collins,Colorado,United States,"40.5832, -105.042"
5953,Miller High Life,5.000000,North American Lager,Miller Brewing,3939 W. Highland Blvd,Milwaukee,Wisconsin,United States,"43.0445, -87.9626"
5954,Jolly Scot Scottish Ale,5.200000,British Ale,Appalachian Brewing Company,50 N. Cameron St.,Harrisburg,Pennsylvania,United States,"40.2659, -76.8753"
5955,Sophie's Sparkling Ale,4.300000,NaN,Appalachian Brewing Company,50 N. Cameron St.,Harrisburg,Pennsylvania,United States,"40.2659, -76.8753"
5956,Harvest Moon Pumpkin,5.700000,Other Style,Coors Brewing - Golden Brewery,311 Tenth Street,Golden,Colorado,United States,"39.7599, -105.219"
5957,Mt. Nittany Pale Ale,5.000000,North American Ale,Otto's Pub and Brewery,2105 N. Atherton St.,State College,Pennsylvania,United States,"40.8098, -77.9101"
5958,Tripel Ale,9.600000,Belgian and French Ale,Otto's Pub and Brewery,2105 N. Atherton St.,State College,Pennsylvania,United States,"40.8098, -77.9101"
5959,Dubbel Ale,5.200000,Belgian and French Ale,Otto's Pub and Brewery,2105 N. Atherton St.,State College,Pennsylvania,United States,"40.8098, -77.9101"
5960,Arthur's Nugget Pale Ale,5.200000,North American Ale,Otto's Pub and Brewery,2105 N. Atherton St.,State College,Pennsylvania,United States,"40.8098, -77.9101"
5961,Augustiner,4.300000,North American Lager,Iron City Brewing Co.,3340 Liberty Ave.,Pittsburgh,Pennsylvania,United States,"40.461, -79.9653"
5962,Lancaster Hefe Weizen,6.000000,German Ale,Lancaster Brewing Co.,302 N. Plum St.,Lancaster,Pennsylvania,United States,"40.0438, -76.2984"
5963,Samuel Adams Black Lager,4.900000,German Lager,Boston Beer Company,30 Germania Street,Boston,Massachusetts,United States,"42.3144, -71.1034"
5964,Double Simcoe IPA,9.000000,North American Ale,Weyerbacher Brewing Company,905 Line Street,Easton,Pennsylvania,United States,"40.6732, -75.2249"
5965,Garde Dog,5.800000,NaN,Flying Dog Brewery,2401 Blake St.,Denver,Colorado,United States,"39.7582, -104.99"
5966,Pliny the Elder,8.000000,North American Ale,Russian River Brewing,725 Fourth Street,Santa Rosa,California,United States,"38.4418, -122.712"
5967,Erdinger Weizen,5.300000,Other Style,Privatbrauerei Erdinger Weissbru,Franz-Brombach-Strae 1-20,Erding,Bayern,Germany,"48.3153, 11.8911"
5968,McCafferty's Ale,3.379987,Irish Ale,North Country Brewery,141 South Main Street,Slippery Rock,Pennsylvania,United States,"41.0638, -80.0556"
5969,Boltwood Bock,5.700000,German Lager,Amherst Brewing Company,24 North Pleasant Street,Amherst,Massachusetts,United States,"42.3763, -72.5199"
5970,Bad Penny,5.500000,North American Ale,Big Boss Brewing Company,1249-A Wicker Drive,Raleigh,North Carolina,United States,"35.8104, -78.6179"
5971,Saranac Golden Pilsner,5.100000,German Lager,F.X. Matt Brewing,811 Edward Street,Utica,New York,United States,"43.1045, -75.2452"
5972,Saranac Pumpkin Ale,5.400000,Other Style,F.X. Matt Brewing,811 Edward Street,Utica,New York,United States,"43.1045, -75.2452"

In [237]:
df1 = df1.fillna(0)
pre_data = df1.as_matrix()

In [234]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(pre_data[:,0])
lb_y = le.transform(y_data_training)

array([['Scottish Ale', 5.8000001907000005, 'British Ale', ..., 'Illinois',
        'United States', '42.2689, -89.0907'],
       ['Het Kapittel Pater', 3.379986550756396, 0, ..., 'West-Vlaanderen',
        'Belgium', '50.8612, 2.6615'],
       ['Export Premium', 5.400000095399999, 0, ..., 'Hessen', 'Germany',
        '50.5208, 8.8166'],
       ...,
       ['Bad Penny', 5.5, 'North American Ale', ..., 'North Carolina',
        'United States', '35.8104, -78.6179'],
       ['Saranac Golden Pilsner', 5.0999999046, 'German Lager', ...,
        'New York', 'United States', '43.1045, -75.2452'],
       ['Saranac Pumpkin Ale', 5.400000095399999, 'Other Style', ...,
        'New York', 'United States', '43.1045, -75.2452']], dtype=object)

In [227]:
y_data = df1["Category"]
x_data = df1.loc[:,df1.columns != "Category"]

In [228]:
y_data_training = y_data[y_data != 0]
y_data_test=y_data[y_data == 0]

x_data_training = x_data[y_data != 0]
x_data_test=x_data[y_data == 0]

In [229]:
y_data_training

0                  British Ale
3           North American Ale
11                  German Ale
12                German Lager
15                German Lager
17          North American Ale
18                German Lager
20          North American Ale
22          North American Ale
23                 British Ale
24          North American Ale
27                German Lager
28                   Irish Ale
29        North American Lager
30        North American Lager
31          North American Ale
32                 British Ale
35          North American Ale
37          North American Ale
38          North American Ale
39                  German Ale
41                German Lager
43        North American Lager
44          North American Ale
45                  German Ale
46        North American Lager
48                   Irish Ale
49        North American Lager
50                German Lager
53                   Irish Ale
                 ...
5941               Other Style
5942                German Ale
5943        North American Ale
5944        North American Ale
5945        North American Ale
5946        North American Ale
5947    Belgian and French Ale
5948        North American Ale
5949              German Lager
5950               Other Style
5951        North American Ale
5952      North American Lager
5953      North American Lager
5954               British Ale
5956               Other Style
5957        North American Ale
5958    Belgian and French Ale
5959    Belgian and French Ale
5960        North American Ale
5961      North American Lager
5962                German Ale
5963              German Lager
5964        North American Ale
5966        North American Ale
5967               Other Style
5968                 Irish Ale
5969              German Lager
5970        North American Ale
5971              German Lager
5972               Other Style
Name: Category, Length: 4466, dtype: object

In [230]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_data_training)
lb_y = le.transform(y_data_training)

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
        ...
5943    True
5944    True
5945    True
5946    True
5947    True
5948    True
5949    True
5950    True
5951    True
5952    True
5953    True
5954    True
5955    True
5956    True
5957    True
5958    True
5959    True
5960    True
5961    True
5962    True
5963    True
5964    True
5965    True
5966    True
5967    True
5968    True
5969    True
5970    True
5971    True
5972    True
Name: Category, Length: 5973, dtype: bool